### ISSUE TITLE
L.whatever.extend is not a function

### ISSUE THREAD

**Issue by indigoxela** [Falke-Design/Leaflet-V1-polyfill#12]
With latest dev and latest polyfill.

Caused by https://github.com/Leaflet/Leaflet/pull/10006

That means everything breaks again. My whole integration and all plugins. Not sure, if this can be fixed, or if it's even worth it, as the initialize() method's the next on the list to get dropped.
But if there's a way to fix both in the polyfill, I'd be really happy.

TBH, it's hard to stay optimistic, if even more breaking changes are still pending. I know, still the alpha phase for L, but... from an integrator's perspective this policy's frustrating. Not your fault, I know, @Falke-Design

**Comment by Falke-Design** [comment]
Polyfill for Class.extend added.

I think currently the best way is to stick with V1. Saddly they other maintainers want to refactor more, which will cause that the old plugins will be not compatible anymore. This polyfill can't fix that anymore.

**Comment by indigoxela** [comment]
I totally understand. Thank you so much for your effort. 👍
